#!/bin/bash

## Description: import given test data into ddev (database and configurations)
## Usage: initialize
## Example: "ddev import-data"

if ! command -v "git-lfs" &> /dev/null
then
    echo "COMMAND "git lfs" could not be found"
    echo "Please install git-lfs support, see: https://git-lfs.github.com/"
    exit
fi

git lfs pull
ddev import-db --src=.project/data/db.sql.gz
cp .build/vendor/typo3/cms-install/Resources/Private/FolderStructureTemplateFiles/root-htaccess .build/public/.htaccess
mkdir -p config/sites/main && cp .project/typo3/config.yaml config/sites/main/
mkdir -p config/system && cp .project/typo3/settings.php config/system
mkdir -p .build/public/config/ipandlanguageredirect && cp .project/typo3/redirect.php .build/public/config/ipandlanguageredirect/
